dataByType[ITEM_TYPES.Bug] = {
  "2": {
    name: "agrias butterfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins6.png",
    sellPrice: "3000",
    location: "Flying near flowers",
    weather: "No rain",
    rarity: "Uncommon",
    timeRanges: "8am-5pm",
    monthRanges: "Apr-Sept",
  },
  "3": {
    name: "ant",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins26.png",
    sellPrice: "80",
    location: "On rotten turnips",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "4": {
    name: "Atlas moth",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins10.png",
    sellPrice: "3000",
    location: "On trees (any kind)",
    weather: "Any",
    rarity: "Uncommon",
    timeRanges: "7pm-4am",
    monthRanges: "Apr-Sept",
  },
  "5": {
    name: "bagworm",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins36.png",
    sellPrice: "600",
    location: "Shaking trees (hardwood or cedar only)",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "6": {
    name: "banded dragonfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins24.png",
    sellPrice: "4500",
    location: "Flying near water",
    weather: "No rain",
    rarity: "Rare",
    timeRanges: "8am-5pm",
    monthRanges: "May-Oct",
  },
  "7": {
    name: "bell cricket",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins31.png",
    sellPrice: "430",
    location: "On the ground",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "5pm-8am",
    monthRanges: "Sept-Oct",
  },
  "8": {
    name: "blue weevil beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins80.png",
    sellPrice: "800",
    location: "On palm trees",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "Jul-Aug",
  },
  "9": {
    name: "brown cicada",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins17.png",
    sellPrice: "250",
    location: "On hardwood/cedar trees",
    weather: "Any",
    rarity: "Common",
    timeRanges: "8am-5pm",
    monthRanges: "Jul-Aug",
  },
  "10": {
    name: "centipede",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins60.png",
    sellPrice: "300",
    location: "From hitting rocks",
    weather: "Any",
    rarity: "Common",
    timeRanges: "4pm-11pm",
    monthRanges: "Sept-Jun",
  },
  "11": {
    name: "cicada shell",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins69.png",
    sellPrice: "10",
    location: "On hardwood/cedar trees",
    weather: "Any",
    rarity: "Rare",
    timeRanges: "All Day",
    monthRanges: "Jul-Aug",
  },
  "12": {
    name: "citrus long-horned beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins39.png",
    sellPrice: "350",
    location: "On tree stumps",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "13": {
    name: "common bluebottle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins72.png",
    sellPrice: "300",
    location: "Flying",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "4am-7pm",
    monthRanges: "Apr-Aug",
  },
  "14": {
    name: "common butterfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins0.png",
    sellPrice: "160",
    location: "Flying",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "4am-7pm",
    monthRanges: "Sept-Jun",
  },
  "15": {
    name: "cricket",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins30.png",
    sellPrice: "130",
    location: "On the ground",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "5pm-8am",
    monthRanges: "Sept-Nov",
  },
  "16": {
    name: "cyclommatus stag",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins49.png",
    sellPrice: "8000",
    location: "On palm trees",
    weather: "Any",
    rarity: "Ultra-rare",
    timeRanges: "5pm-8am",
    monthRanges: "Jul-Aug",
  },
  "17": {
    name: "damselfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins81.png",
    sellPrice: "500",
    location: "Flying near water",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "Nov-Feb",
  },
  "18": {
    name: "darner dragonfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins23.png",
    sellPrice: "230",
    location: "Flying near water",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "8am-5pm",
    monthRanges: "Apr-Oct",
  },
  "19": {
    name: "diving beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins28.png",
    sellPrice: "800",
    location: "On rivers/ponds",
    weather: "Any",
    rarity: "Common",
    timeRanges: "8am-7pm",
    monthRanges: "May-Sept",
  },
  "20": {
    name: "drone beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins75.png",
    sellPrice: "200",
    location: "On trees (any kind)",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "Jun-Aug",
  },
  "21": {
    name: "dung beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins40.png",
    sellPrice: "3000",
    location: "Pushing snowballs",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "Dec-Feb",
  },
  "22": {
    name: "earth-boring dung beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins42.png",
    sellPrice: "300",
    location: "On the ground",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "Jul-Sept",
  },
  "23": {
    name: "emperor butterfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins5.png",
    sellPrice: "4000",
    location: "Flying near flowers",
    weather: "No rain",
    rarity: "Uncommon",
    timeRanges: "5pm-8am",
    monthRanges: "Dec-Mar,Jun-Sept",
  },
  "24": {
    name: "evening cicada",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins20.png",
    sellPrice: "550",
    location: "On hardwood/cedar trees",
    weather: "Any",
    rarity: "Common",
    timeRanges: "4am-8am, 4pm-7pm",
    monthRanges: "Jul-Aug",
  },
  "25": {
    name: "firefly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins41.png",
    sellPrice: "300",
    location: "Flying near water",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "7pm-4am",
    monthRanges: "Jun-Jun",
  },
  "26": {
    name: "flea",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins56.png",
    sellPrice: "70",
    location: "On villagers",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "Apr-Nov",
  },
  "27": {
    name: "fly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins59.png",
    sellPrice: "60",
    location: "Flying near trash (boots, tires, cans) or rotten turnips",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "28": {
    name: "giant cicada",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins65.png",
    sellPrice: "500",
    location: "On hardwood/cedar trees",
    weather: "Any",
    rarity: "Uncommon",
    timeRanges: "8am-5pm",
    monthRanges: "Jul-Aug",
  },
  "29": {
    name: "giant stag",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins47.png",
    sellPrice: "10000",
    location: "On trees (any kind)",
    weather: "Any",
    rarity: "Rare",
    timeRanges: "11pm-8am",
    monthRanges: "Jul-Aug",
  },
  "30": {
    name: "giant water bug",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins76.png",
    sellPrice: "2000",
    location: "On rivers/ponds",
    weather: "Any",
    rarity: "Rare",
    timeRanges: "7pm-8am",
    monthRanges: "Apr-Sept",
  },
  "31": {
    name: "giraffe stag",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins77.png",
    sellPrice: "12000",
    location: "On palm trees",
    weather: "Any",
    rarity: "Ultra-rare",
    timeRanges: "5pm-8am",
    monthRanges: "Jul-Aug",
  },
  "32": {
    name: "golden stag",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins50.png",
    sellPrice: "12000",
    location: "On palm trees",
    weather: "Any",
    rarity: "Ultra-rare",
    timeRanges: "5pm-8am",
    monthRanges: "Jul-Aug",
  },
  "33": {
    name: "goliath beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins55.png",
    sellPrice: "8000",
    location: "On palm trees",
    weather: "Any",
    rarity: "Ultra-rare",
    timeRanges: "5pm-8am",
    monthRanges: "Jun-Sept",
  },
  "34": {
    name: "grasshopper",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins32.png",
    sellPrice: "160",
    location: "On the ground",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "8am-5pm",
    monthRanges: "Jul-Sept",
  },
  "35": {
    name: "great purple emperor",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins74.png",
    sellPrice: "3000",
    location: "Flying near flowers",
    weather: "No rain",
    rarity: "Rare",
    timeRanges: "4am-7pm",
    monthRanges: "May-Aug",
  },
  "36": {
    name: "hermit crab",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins66.png",
    sellPrice: "1000",
    location: "Disguised on shoreline",
    weather: "Any",
    rarity: "Common",
    timeRanges: "7pm-8am",
    monthRanges: "All Year",
  },
  "37": {
    name: "honeybee",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins11.png",
    sellPrice: "200",
    location: "Flying near flowers",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "8am-5pm",
    monthRanges: "Mar-Jul",
  },
  "38": {
    name: "horned atlas",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins52.png",
    sellPrice: "8000",
    location: "On palm trees",
    weather: "Any",
    rarity: "Ultra-rare",
    timeRanges: "5pm-8am",
    monthRanges: "Jul-Aug",
  },
  "39": {
    name: "horned dynastid",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins51.png",
    sellPrice: "1350",
    location: "On trees (any kind)",
    weather: "Any",
    rarity: "Common",
    timeRanges: "5pm-8am",
    monthRanges: "Jul-Aug",
  },
  "40": {
    name: "horned elephant",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins53.png",
    sellPrice: "8000",
    location: "On palm trees",
    weather: "Any",
    rarity: "Ultra-rare",
    timeRanges: "5pm-8am",
    monthRanges: "Jul-Aug",
  },
  "41": {
    name: "horned hercules",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins54.png",
    sellPrice: "12000",
    location: "On palm trees",
    weather: "Any",
    rarity: "Ultra-rare",
    timeRanges: "5pm-8am",
    monthRanges: "Jul-Aug",
  },
  "42": {
    name: "jewel beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins44.png",
    sellPrice: "2400",
    location: "On tree stumps",
    weather: "No rain",
    rarity: "Uncommon",
    timeRanges: "All Day",
    monthRanges: "Apr-Aug",
  },
  "43": {
    name: "ladybug",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins37.png",
    sellPrice: "200",
    location: "On flowers",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "8am-5pm",
    monthRanges: "Mar-Jun,Oct-Oct",
  },
  "44": {
    name: "long locust",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins13.png",
    sellPrice: "200",
    location: "On the ground",
    weather: "Any",
    rarity: "Common",
    timeRanges: "8am-7pm",
    monthRanges: "Apr-Nov",
  },
  "45": {
    name: "Madagascan sunset moth",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins79.png",
    sellPrice: "2500",
    location: "Flying near flowers",
    weather: "No rain",
    rarity: "Uncommon",
    timeRanges: "8am-4pm",
    monthRanges: "Apr-Sept",
  },
  "46": {
    name: "man-faced stink bug",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins78.png",
    sellPrice: "1000",
    location: "On flowers",
    weather: "No rain",
    rarity: "Uncommon",
    timeRanges: "7pm-8am",
    monthRanges: "Mar-Oct",
  },
  "47": {
    name: "mantis",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins15.png",
    sellPrice: "430",
    location: "On flowers",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "8am-5pm",
    monthRanges: "Mar-Nov",
  },
  "48": {
    name: "migratory locust",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins14.png",
    sellPrice: "600",
    location: "On the ground",
    weather: "Any",
    rarity: "Uncommon",
    timeRanges: "8am-7pm",
    monthRanges: "Aug-Nov",
  },
  "49": {
    name: "miyama stag",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins46.png",
    sellPrice: "1000",
    location: "On trees (any kind)",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "Jul-Aug",
  },
  "50": {
    name: "mole cricket",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins33.png",
    sellPrice: "500",
    location: "Underground (dig where noise is loudest)",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "Nov-May",
  },
  "51": {
    name: "monarch butterfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins4.png",
    sellPrice: "140",
    location: "Flying near flowers",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "4am-5pm",
    monthRanges: "Sept-Nov",
  },
  "52": {
    name: "mosquito",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins58.png",
    sellPrice: "130",
    location: "Flying",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "5pm-4am",
    monthRanges: "Jun-Sept",
  },
  "53": {
    name: "moth",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins9.png",
    sellPrice: "130",
    location: "Flying near light sources",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "7pm-4am",
    monthRanges: "All Year",
  },
  "54": {
    name: "orchid mantis",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins16.png",
    sellPrice: "2400",
    location: "On white flowers",
    weather: "No rain",
    rarity: "Uncommon",
    timeRanges: "8am-5pm",
    monthRanges: "Mar-Nov",
  },
  "55": {
    name: "paper kite butterfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins73.png",
    sellPrice: "1000",
    location: "Flying near flowers",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "8am-7pm",
    monthRanges: "All Year",
  },
  "56": {
    name: "peacock butterfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins3.png",
    sellPrice: "2500",
    location: "Flying near blue/purple/black flowers",
    weather: "No rain",
    rarity: "Uncommon",
    timeRanges: "4am-7pm",
    monthRanges: "Mar-Jun",
  },
  "57": {
    name: "pill bug",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins57.png",
    sellPrice: "250",
    location: "From hitting rocks",
    weather: "Any",
    rarity: "Common",
    timeRanges: "11pm-4pm",
    monthRanges: "Sept-Jun",
  },
  "58": {
    name: "pondskater",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins27.png",
    sellPrice: "130",
    location: "On rivers/ponds",
    weather: "Any",
    rarity: "Common",
    timeRanges: "8am-7pm",
    monthRanges: "May-Sept",
  },
  "59": {
    name: "Queen Alexandra's birdwing",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins8.png",
    sellPrice: "4000",
    location: "Flying near flowers",
    weather: "No rain",
    rarity: "Rare",
    timeRanges: "8am-4pm",
    monthRanges: "May-Sept",
  },
  "60": {
    name: "rainbow stag",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins48.png",
    sellPrice: "6000",
    location: "On trees (any kind)",
    weather: "Any",
    rarity: "Rare",
    timeRanges: "7pm-8am",
    monthRanges: "Jun-Sept",
  },
  "61": {
    name: "Rajah Brooke's birdwing",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins7.png",
    sellPrice: "2500",
    location: "Flying near flowers",
    weather: "No rain",
    rarity: "Uncommon",
    timeRanges: "8am-5pm",
    monthRanges: "Dec-Feb,Apr-Sept",
  },
  "62": {
    name: "red dragonfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins22.png",
    sellPrice: "180",
    location: "Flying near water",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "8am-7pm",
    monthRanges: "Sept-Oct",
  },
  "63": {
    name: "rice grasshopper",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins67.png",
    sellPrice: "400",
    location: "On the ground",
    weather: "Any",
    rarity: "Common",
    timeRanges: "8am-7pm",
    monthRanges: "Aug-Nov",
  },
  "64": {
    name: "robust cicada",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins18.png",
    sellPrice: "300",
    location: "On hardwood/cedar trees",
    weather: "Any",
    rarity: "Common",
    timeRanges: "8am-5pm",
    monthRanges: "Jul-Aug",
  },
  "65": {
    name: "rosalia batesi beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins82.png",
    sellPrice: "3000",
    location: "On tree stumps",
    weather: "No rain",
    rarity: "Uncommon",
    timeRanges: "All Day",
    monthRanges: "May-Sept",
  },
  "66": {
    name: "saw stag",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins46.png",
    sellPrice: "2000",
    location: "On trees (any kind)",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "Jul-Aug",
  },
  "67": {
    name: "scarab beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins43.png",
    sellPrice: "10000",
    location: "On trees (any kind)",
    weather: "Any",
    rarity: "Rare",
    timeRanges: "11pm-8pm",
    monthRanges: "Jul-Aug",
  },
  "68": {
    name: "scorpion",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins63.png",
    sellPrice: "8000",
    location: "On the ground",
    weather: "Any",
    rarity: "Common",
    timeRanges: "7pm-4am",
    monthRanges: "May-Oct",
  },
  "69": {
    name: "snail",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins29.png",
    sellPrice: "250",
    location: "On rocks/bushes",
    weather: "Rain only",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "70": {
    name: "spider",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins61.png",
    sellPrice: "600",
    location: "Shaking trees (hardwood or cedar only)",
    weather: "Any",
    rarity: "Common",
    timeRanges: "7pm-8am",
    monthRanges: "All Year",
  },
  "71": {
    name: "stinkbug",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins64.png",
    sellPrice: "120",
    location: "On flowers",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "Mar-Oct",
  },
  "72": {
    name: "tarantula",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins62.png",
    sellPrice: "8000",
    location: "On the ground",
    weather: "Any",
    rarity: "Common",
    timeRanges: "7pm-4am",
    monthRanges: "Nov-Apr",
  },
  "73": {
    name: "tiger beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins70.png",
    sellPrice: "1500",
    location: "On the ground",
    weather: "No rain",
    rarity: "Uncommon",
    timeRanges: "All Day",
    monthRanges: "Feb-Oct",
  },
  "74": {
    name: "tiger butterfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins2.png",
    sellPrice: "240",
    location: "Flying",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "4am-7pm",
    monthRanges: "Mar-Sept",
  },
  "75": {
    name: "violin beetle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins38.png",
    sellPrice: "450",
    location: "On tree stumps",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "May-Jun,Sept-Nov",
  },
  "76": {
    name: "walker cicada",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins19.png",
    sellPrice: "400",
    location: "On hardwood/cedar trees",
    weather: "Any",
    rarity: "Common",
    timeRanges: "8am-5pm",
    monthRanges: "Aug-Sept",
  },
  "77": {
    name: "walking leaf",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins34.png",
    sellPrice: "600",
    location: "Disguised under trees",
    weather: "Any",
    rarity: "Uncommon",
    timeRanges: "All Day",
    monthRanges: "Jul-Sept",
  },
  "78": {
    name: "walking stick",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins35.png",
    sellPrice: "600",
    location: "On trees (any kind)",
    weather: "Any",
    rarity: "Uncommon",
    timeRanges: "4am-8am, 5pm-7pm",
    monthRanges: "Jun-Nov",
  },
  "79": {
    name: "wasp",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins12.png",
    sellPrice: "2500",
    location: "Shaking trees",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "80": {
    name: "wharf roach",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins71.png",
    sellPrice: "200",
    location: "On beach rocks",
    weather: "Any",
    rarity: "Common",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "81": {
    name: "yellow butterfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Ins1.png",
    sellPrice: "160",
    location: "Flying",
    weather: "No rain",
    rarity: "Common",
    timeRanges: "4am-7pm",
    monthRanges: "Mar-Jun,Sept-Oc",
  },
};
