dataByType[ITEM_TYPES.Fish] = {
  "2": {
    name: "anchovy",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish81.png",
    sellPrice: "200",
    location: "Sea",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4am-9pm",
    monthRanges: "All Year",
  },
  "3": {
    name: "angelfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish30.png",
    sellPrice: "3000",
    location: "River",
    shadowSize: "Small",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "May-Oct",
  },
  "4": {
    name: "arapaima",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish36.png",
    sellPrice: "10000",
    location: "River",
    shadowSize: "XX-Large",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "4pm-9am",
    monthRanges: "Jun-Sept",
  },
  "5": {
    name: "arowana",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish33.png",
    sellPrice: "10000",
    location: "River",
    shadowSize: "Large",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "Jun-Sept",
  },
  "6": {
    name: "barred knifejaw",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish47.png",
    sellPrice: "5000",
    location: "Sea",
    shadowSize: "Medium",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Mar-Nov",
  },
  "7": {
    name: "barreleye",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish84.png",
    sellPrice: "15000",
    location: "Sea",
    shadowSize: "Small",
    rarity: "Ultra-rare",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9pm-4am",
    monthRanges: "All Year",
  },
  "8": {
    name: "betta",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish77.png",
    sellPrice: "2500",
    location: "River",
    shadowSize: "Small",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm",
    monthRanges: "May-Oct",
  },
  "9": {
    name: "bitterling",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish0.png",
    sellPrice: "900",
    location: "River",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Nov-Mar",
  },
  "10": {
    name: "black bass",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish19.png",
    sellPrice: "400",
    location: "River",
    shadowSize: "Large",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "11": {
    name: "blowfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish73.png",
    sellPrice: "5000",
    location: "Sea",
    shadowSize: "Medium",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9pm-5am",
    monthRanges: "Nov-Feb",
  },
  "12": {
    name: "blue marlin",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish58.png",
    sellPrice: "10000",
    location: "Pier",
    shadowSize: "XX-Large",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "All Day",
    monthRanges: "Nov-Apr, Jul-Sept",
  },
  "13": {
    name: "bluegill",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish17.png",
    sellPrice: "180",
    location: "River",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm",
    monthRanges: "All Year",
  },
  "14": {
    name: "butterfly fish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish42.png",
    sellPrice: "1000",
    location: "Sea",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Apr-Sept",
  },
  "15": {
    name: "carp",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish5.png",
    sellPrice: "300",
    location: "Pond",
    shadowSize: "Large",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "16": {
    name: "catfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish14.png",
    sellPrice: "800",
    location: "Pond",
    shadowSize: "Large",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "May-Oct",
  },
  "17": {
    name: "char",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish24.png",
    sellPrice: "3800",
    location: "River (clifftop)",
    shadowSize: "Medium",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "Mar-Jun, Sept-Nov",
  },
  "18": {
    name: "cherry salmon",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish23.png",
    sellPrice: "1000",
    location: "River (clifftop)",
    shadowSize: "Medium",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "Mar-Jun, Sept-Nov",
  },
  "19": {
    name: "clown fish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish40.png",
    sellPrice: "650",
    location: "Sea",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Apr-Sept",
  },
  "20": {
    name: "coelacanth",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish63.png",
    sellPrice: "15000",
    location: "Sea (raining)",
    shadowSize: "XX-Large",
    rarity: "Ultra-rare",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "21": {
    name: "crawfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish10.png",
    sellPrice: "200",
    location: "Pond",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Apr-Sept",
  },
  "22": {
    name: "crucian carp",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish2.png",
    sellPrice: "160",
    location: "River",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "23": {
    name: "dab",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish50.png",
    sellPrice: "300",
    location: "Sea",
    shadowSize: "Medium",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Oct-Apr",
  },
  "24": {
    name: "dace",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish3.png",
    sellPrice: "240",
    location: "River",
    shadowSize: "Medium",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "All Year",
  },
  "25": {
    name: "dorado",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish34.png",
    sellPrice: "15000",
    location: "River",
    shadowSize: "X-Large",
    rarity: "Ultra-rare",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4am-9pm",
    monthRanges: "Jun-Sept",
  },
  "26": {
    name: "football fish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish56.png",
    sellPrice: "2500",
    location: "Sea",
    shadowSize: "Large",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "Nov-Mar",
  },
  "27": {
    name: "freshwater goby",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish12.png",
    sellPrice: "400",
    location: "River",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "All Year",
  },
  "28": {
    name: "frog",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish11.png",
    sellPrice: "120",
    location: "Pond",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "May-Aug",
  },
  "29": {
    name: "gar",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish35.png",
    sellPrice: "6000",
    location: "Pond",
    shadowSize: "X-Large",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "Jun-Sept",
  },
  "30": {
    name: "giant snakehead",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish16.png",
    sellPrice: "5500",
    location: "Pond",
    shadowSize: "Large",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm",
    monthRanges: "Jun-Aug",
  },
  "31": {
    name: "giant trevally",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish70.png",
    sellPrice: "4500",
    location: "Pier",
    shadowSize: "X-Large",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "May-Oct",
  },
  "32": {
    name: "golden trout",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish79.png",
    sellPrice: "15000",
    location: "River (clifftop)",
    shadowSize: "Medium",
    rarity: "Ultra-rare",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "Mar-May, Sept-Nov",
  },
  "33": {
    name: "goldfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish7.png",
    sellPrice: "1300",
    location: "Pond",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "34": {
    name: "great white shark",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish62.png",
    sellPrice: "15000",
    location: "Sea",
    shadowSize: "Large w/Fin",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "4pm-9am",
    monthRanges: "Jun-Sept",
  },
  "35": {
    name: "guppy",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish29.png",
    sellPrice: "1300",
    location: "River",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm",
    monthRanges: "Apr-Nov",
  },
  "36": {
    name: "hammerhead shark",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish61.png",
    sellPrice: "8000",
    location: "Sea",
    shadowSize: "Large w/Fin",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "4pm-9am",
    monthRanges: "Jun-Sept",
  },
  "37": {
    name: "horse mackerel",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish46.png",
    sellPrice: "150",
    location: "Sea",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "38": {
    name: "killifish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish9.png",
    sellPrice: "300",
    location: "Pond",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Apr-Aug",
  },
  "39": {
    name: "king salmon",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish28.png",
    sellPrice: "1800",
    location: "River (mouth)",
    shadowSize: "X-Large",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Sept-Sept",
  },
  "40": {
    name: "koi",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish6.png",
    sellPrice: "4000",
    location: "Pond",
    shadowSize: "Large",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "All Year",
  },
  "41": {
    name: "loach",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish13.png",
    sellPrice: "400",
    location: "River",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Mar-May",
  },
  "42": {
    name: "mahi-mahi",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish82.png",
    sellPrice: "6000",
    location: "Pier",
    shadowSize: "X-Large",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "All Day",
    monthRanges: "May-Oct",
  },
  "43": {
    name: "mitten crab",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish66.png",
    sellPrice: "2000",
    location: "River",
    shadowSize: "Small",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "Sept-Nov",
  },
  "44": {
    name: "moray eel",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish55.png",
    sellPrice: "2000",
    location: "Sea",
    shadowSize: "Long",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Aug-Oct",
  },
  "45": {
    name: "Napoleonfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish43.png",
    sellPrice: "10000",
    location: "Sea",
    shadowSize: "XX-Large",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "4am-9pm",
    monthRanges: "Jul-Aug",
  },
  "46": {
    name: "neon tetra",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish31.png",
    sellPrice: "500",
    location: "River",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm",
    monthRanges: "Apr-Nov",
  },
  "47": {
    name: "nibble fish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish67.png",
    sellPrice: "1500",
    location: "River",
    shadowSize: "X-Small",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm",
    monthRanges: "May-Sept",
  },
  "48": {
    name: "oarfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish69.png",
    sellPrice: "9000",
    location: "Sea",
    shadowSize: "XX-Large",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "All Day",
    monthRanges: "Dec-May",
  },
  "49": {
    name: "ocean sunfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish60.png",
    sellPrice: "4000",
    location: "Sea",
    shadowSize: "Large w/Fin",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "4am-9pm",
    monthRanges: "Jul-Sept",
  },
  "50": {
    name: "olive flounder",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish51.png",
    sellPrice: "800",
    location: "Sea",
    shadowSize: "X-Large",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "51": {
    name: "pale chub",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish1.png",
    sellPrice: "200",
    location: "River",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm",
    monthRanges: "All Year",
  },
  "52": {
    name: "pike",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish20.png",
    sellPrice: "1800",
    location: "River",
    shadowSize: "X-Large",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Sept-Dec",
  },
  "53": {
    name: "piranha",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish32.png",
    sellPrice: "2500",
    location: "River",
    shadowSize: "Small",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm, 9pm-4am",
    monthRanges: "Jun-Sept",
  },
  "54": {
    name: "pond smelt",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish21.png",
    sellPrice: "400",
    location: "River",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Dec-Feb",
  },
  "55": {
    name: "pop-eyed goldfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish8.png",
    sellPrice: "1300",
    location: "Pond",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm",
    monthRanges: "All Year",
  },
  "56": {
    name: "puffer fish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish45.png",
    sellPrice: "250",
    location: "Sea",
    shadowSize: "Medium",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Jul-Sept",
  },
  "57": {
    name: "rainbowfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish80.png",
    sellPrice: "800",
    location: "River",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm",
    monthRanges: "May-Oct",
  },
  "58": {
    name: "ranchu goldfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish85.png",
    sellPrice: "4500",
    location: "Pond",
    shadowSize: "Small",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9am-4pm",
    monthRanges: "All Year",
  },
  "59": {
    name: "ray",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish59.png",
    sellPrice: "3000",
    location: "Sea",
    shadowSize: "X-Large",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4am-9pm",
    monthRanges: "Aug-Nov",
  },
  "60": {
    name: "red snapper",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish49.png",
    sellPrice: "3000",
    location: "Sea",
    shadowSize: "Large",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "61": {
    name: "ribbon eel",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish71.png",
    sellPrice: "600",
    location: "Sea",
    shadowSize: "Long",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Jun-Oct",
  },
  "62": {
    name: "saddled bichir",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish68.png",
    sellPrice: "4000",
    location: "River",
    shadowSize: "Large",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9pm-4am",
    monthRanges: "Jun-Sept",
  },
  "63": {
    name: "salmon",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish27.png",
    sellPrice: "700",
    location: "River (mouth)",
    shadowSize: "Large",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Sept-Sept",
  },
  "64": {
    name: "saw shark",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish74.png",
    sellPrice: "12000",
    location: "Sea",
    shadowSize: "Large w/Fin",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "Jun-Sept",
  },
  "65": {
    name: "sea bass",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish48.png",
    sellPrice: "400",
    location: "Sea",
    shadowSize: "X-Large",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "All Year",
  },
  "66": {
    name: "sea butterfly",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish37.png",
    sellPrice: "1000",
    location: "Sea",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Dec-Mar",
  },
  "67": {
    name: "sea horse",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish39.png",
    sellPrice: "1100",
    location: "Sea",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Apr-Nov",
  },
  "68": {
    name: "snapping turtle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish78.png",
    sellPrice: "5000",
    location: "River",
    shadowSize: "Large",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "9pm-4am",
    monthRanges: "Apr-Oct",
  },
  "69": {
    name: "soft-shelled turtle",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish65.png",
    sellPrice: "3750",
    location: "River",
    shadowSize: "Large",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "Aug-Sept",
  },
  "70": {
    name: "squid",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish52.png",
    sellPrice: "500",
    location: "Sea",
    shadowSize: "Medium",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Dec-Aug",
  },
  "71": {
    name: "stringfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish26.png",
    sellPrice: "15000",
    location: "River (clifftop)",
    shadowSize: "X-Large",
    rarity: "Ultra-rare",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "4pm-9am",
    monthRanges: "Dec-Mar",
  },
  "72": {
    name: "sturgeon",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish75.png",
    sellPrice: "10000",
    location: "River (mouth)",
    shadowSize: "XX-Large",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "All Day",
    monthRanges: "Sept-Mar",
  },
  "73": {
    name: "suckerfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish83.png",
    sellPrice: "1500",
    location: "Sea",
    shadowSize: "Medium w/Fin",
    rarity: "Uncommon",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Jun-Sept",
  },
  "74": {
    name: "surgeonfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish41.png",
    sellPrice: "1000",
    location: "Sea",
    shadowSize: "Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Apr-Sept",
  },
  "75": {
    name: "sweetfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish22.png",
    sellPrice: "900",
    location: "River",
    shadowSize: "Medium",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Jul-Sept",
  },
  "76": {
    name: "tadpole",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish64.png",
    sellPrice: "100",
    location: "Pond",
    shadowSize: "X-Small",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Mar-Jul",
  },
  "77": {
    name: "tilapia",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish76.png",
    sellPrice: "800",
    location: "River",
    shadowSize: "Medium",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Jun-Oct",
  },
  "78": {
    name: "tuna",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish57.png",
    sellPrice: "7000",
    location: "Pier",
    shadowSize: "XX-Large",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "All Day",
    monthRanges: "Nov-Apr",
  },
  "79": {
    name: "whale shark",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish72.png",
    sellPrice: "13000",
    location: "Sea",
    shadowSize: "Large w/Fin",
    rarity: "Rare",
    increasedChanceInRainOrSnow: "Yes",
    timeRanges: "All Day",
    monthRanges: "Jun-Sept",
  },
  "80": {
    name: "yellow perch",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish18.png",
    sellPrice: "300",
    location: "River",
    shadowSize: "Medium",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Oct-Mar",
  },
  "81": {
    name: "zebra turkeyfish",
    iconUrl: "https://acnhcdn.com/latest/MenuIcon/Fish44.png",
    sellPrice: "500",
    location: "Sea",
    shadowSize: "Medium",
    rarity: "Common",
    increasedChanceInRainOrSnow: "No",
    timeRanges: "All Day",
    monthRanges: "Apr-Nov",
  },
};
